#!/usr/bin/env bash
# =============================================================================
# MIZAN — one-command setup from a clean clone.
#
#     ./scripts/setup.sh                 # or: make setup
#
# Builds data/corpus.sqlite (≈124 MB, too large for GitHub, so never committed)
# from the publishers' own official files, verifying every byte on the way:
#
#   1. Quranpedia.net official dump — https://quranpedia.net/dumps/
#        manifest.json + translations-all.zip, then the 22 approved
#        translations MIZAN indexes are extracted and checked twice:
#          * byte size  against the publisher's manifest (translation_books[])
#          * SHA-256    against the values pinned below (the exact content every
#                       published number was measured on)
#   2. Tanzil Quran text (Uthmani + simple-clean) — https://tanzil.net
#        verse lines checked against pinned SHA-256 values.
#   3. scripts/build_index.py, then scripts/fetch_arabic.py.
#   4. The finished index is fingerprinted (python3 -m mizan.eval --check-index)
#      and must equal the reference index the evaluation was run on.
#   5. The redistributable terminology glossary is checked (or regenerated by
#      scripts/export_public_glossary.py when the full local copy exists).
#
# Idempotent: every step is cached under data/raw/ and skipped when its output
# already verifies. A second run downloads nothing and rebuilds nothing.
# Fails loudly — non-zero exit, a message naming the file — on any mismatch.
#
# Options
#   --offline       never touch the network; use data/raw/ only
#   --force         rebuild the index even if it already verifies
#   --per-file      fetch the 22 translation files individually from the dump
#                   host instead of the 64 MB zip (faster; same bytes)
#   --real-corpus   also rebuild data/real/ from the publishers' pages
#                   (scripts/rebuild_real_corpus.py; ~10 min, polite crawl)
#   --no-changes    skip the Quranpedia "changes since" courtesy check
#   -h | --help
#
# Environment
#   PYTHON                         interpreter (default: python3, must be >= 3.11)
#   MIZAN_ALLOW_INDEX_DRIFT=1      warn instead of fail if the built index does
#                                  not match the reference fingerprint
#   MIZAN_ACCEPT_NEW_DUMP=1        accept translation files whose SHA-256 differs
#                                  from the pins (publisher corrected the text).
#                                  Every published number must then be re-measured.
#
# Network etiquette: Quranpedia's usage policy forbids bulk API scraping and
# asks high-volume clients to put a contact address in the User-Agent. We use
# only the official dumps (plus one optional call to the changes endpoint the
# policy itself recommends), sequentially, with the UA below.
# =============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PY="${PYTHON:-python3}"
export MIZAN_UA="Mizan/0.1 (Islamic AI Challenge 2026; contact osamaabdullh2002@gmail.com)"
export MIZAN_ROOT="$ROOT"

# --- sources -----------------------------------------------------------------
export QP_DUMPS="https://quranpedia.net/dumps"
export QP_HOST="https://quranpedia.net"          # manifest URLs say http://localhost
export QP_PINNED_VERSION="2026-10-01"            # dump the pins were taken from
export TANZIL_URL="https://tanzil.net/pub/download/index.php"

# The 22 approved translations MIZAN indexes: SHA-256, file, language.
# Taken from dump 2026-10-01 and re-verified byte-identical in dump 2026-10-03.
# Selection rule: every Quranpedia translation book in English, Tagalog, Urdu,
# Bengali or Hindi. Adding a language = adding its lines here and re-measuring.
export QP_PINNED="
8c08a8332fae34788f556e5d13a78fe45f68f607cf7a2dabd6596a7fad573978  1947.json   en
514db28e78166a8218a825526ac03ff7a80ddb1c13ea43ce1070b145fba688b4  1948.json   en
76915a74e0d92d522e7dc162cd4bcc12d2fcc2f38a6d061260456b33afecec2d  1963.json   tl
17979e35fa76a852d9175ced99f5b0580bb0aa85a0ea1d6f3560e1290ac11563  1966.json   ur
1fac43e830aa94bb8e8b7f1a15f9ce920bd0d3f9dfd5202ac2019644e96cd4f5  1967.json   bn
7d64144fcf2761ea7209d1dd28e27d05714f362e7ac5094da564cc4dc03b2a2e  1986.json   hi
0877c98324799d790414be9053917464beb1da4142a78f5a27860529cc804df4  2010.json   tl
a3d31db96594b510f368014da337460fc32d460329ad227d0da983c7de25a691  13602.json  en
b0322cc719dc9891e2138a135bac90b8176aee811d476388d45d367c0a034dce  13603.json  en
7dad21c07905ad57dfa4645e5451f6d7660a5b7dcc78ce559160484c0c606417  13604.json  en
1c81ae31627ea3a8885dc049e95191e1b91ccc849b235759bef3ed4c8a2b5303  13605.json  en
cdab16c0802d058f97757ca377c29ff57779d226e0a73e0806af8457a3b58b5c  13625.json  ur
3e90569f2cf2ca8ed9f1699f9339bdc08d0e32ba0977885dc55a2fa15bed0f2a  13638.json  en
5d95b76e9ef2f88db0fad6173166c43481d928a16b0244aa52fbc8cab2c0db33  13640.json  en
54797f9992446070a11c3500eb260d6dcffe64e65413f87f39a5b6e7f2587a8b  13644.json  en
e767a10b63f52355893e71357ffa88cde6c2e86db305ccf1de13a33b7db89c6b  13645.json  en
778397d13077ff5e732d913e6e1e7a258c1a77fe379bb89f5f79cece7a377839  13661.json  en
7ce5d0e72246d2c3fc30a236aea6215896a0bcad4ed6c29d7bffa5e1851f42a4  13662.json  en
5bd75450f7abeb04bab1532fd0563cf8620d46abf28bd459775dcdad47899477  27811.json  en
4790ae49369d80d40c63ed8f197c0d6db909bcee23d63288fb12159cab4eccdc  27824.json  en
751b22a7cd593a2b469a9fc3c1f8cb8a18d5b5b990ee91b7f9dc3c23b893eb67  27826.json  bn
26601f74e2174a00d503398bd519b93cfe0522bc75021876c134d1c56a7909da  27833.json  en
"

# Tanzil: SHA-256 of the 6,236 verse lines ("surah|ayah|text"), i.e. the file
# minus its '#' copyright block — the block carries a year that changes every
# January, the verses do not.
export TANZIL_PINNED="
36da55e256f54f4838b6fa1c78781734346c8d9ffde52daf5a3cbfa32626a08c  uthmani
7c74ab21103b99d8d0bacd94e7c11f5f5855b22d3f0d32e1f09fb6cd73764b58  simple-clean
"

# --- options -----------------------------------------------------------------
export MIZAN_OFFLINE=0 MIZAN_PER_FILE=0
FORCE=0 REAL=0 CHANGES=1
for arg in "$@"; do
  case "$arg" in
    --offline)     MIZAN_OFFLINE=1 ;;
    --force)       FORCE=1 ;;
    --per-file)    MIZAN_PER_FILE=1 ;;
    --real-corpus) REAL=1 ;;
    --no-changes)  CHANGES=0 ;;
    -h|--help)     sed -n '2,/^set -euo/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg (see --help)" >&2; exit 2 ;;
  esac
done

# --- output helpers ----------------------------------------------------------
if [ -t 1 ]; then B=$'\033[1m'; G=$'\033[32m'; R=$'\033[31m'; Y=$'\033[33m'; N=$'\033[0m'
else B=""; G=""; R=""; Y=""; N=""; fi
step() { printf '\n%s[%s] %s%s\n' "$B" "$1" "$2" "$N"; }
ok()   { printf '  %sok%s    %s\n' "$G" "$N" "$1"; }
warn() { printf '  %swarn%s  %s\n' "$Y" "$N" "$1"; }
die()  { printf '\n%sFAILED%s %s\n' "$R" "$N" "$1" >&2; exit 1; }

START=$(date +%s)
printf '%sمِيزان — MIZAN setup%s  (%s)\n' "$B" "$N" "$ROOT"

# =============================================================================
step 1/7 "Python"
# =============================================================================
command -v "$PY" >/dev/null 2>&1 || die "$PY not found. Install Python 3.11+."
"$PY" - <<'PY' || die "Python 3.11+ with sqlite3 FTS5 is required (see message above)."
import sqlite3, sys
if sys.version_info < (3, 11):
    sys.exit(f"  found Python {sys.version.split()[0]}, need >= 3.11")
con = sqlite3.connect(":memory:")
try:
    con.execute("CREATE VIRTUAL TABLE t USING fts5(x)")
except sqlite3.OperationalError as exc:
    sys.exit(f"  this Python's sqlite3 lacks FTS5 ({exc})")
print(f"  ok    Python {sys.version.split()[0]} · SQLite {sqlite3.sqlite_version} with FTS5")
PY

mkdir -p data/raw/quranpedia data/raw/tanzil

# =============================================================================
step 2/7 "Quranpedia.net official dump (approved translations)"
# =============================================================================
"$PY" - <<'PY' || die "Quranpedia dump could not be fetched or verified (see above)."
import hashlib, json, os, shutil, sys, time, urllib.request, zipfile

ROOT = os.environ["MIZAN_ROOT"]
UA = os.environ["MIZAN_UA"]
OFFLINE = os.environ["MIZAN_OFFLINE"] == "1"
PER_FILE = os.environ["MIZAN_PER_FILE"] == "1"
ACCEPT_NEW = os.environ.get("MIZAN_ACCEPT_NEW_DUMP") == "1"
RAW = os.path.join(ROOT, "data", "raw")
OUT = os.path.join(RAW, "quranpedia")
MANIFEST = os.path.join(RAW, "manifest.json")
ZIP = os.path.join(RAW, "translations-all.zip")
DUMPS, HOST = os.environ["QP_DUMPS"], os.environ["QP_HOST"]

pinned = {}
for line in os.environ["QP_PINNED"].strip().splitlines():
    sha, name, lang = line.split()
    pinned[name] = (sha, lang)


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def download(url, dest, label, gzip_ok=False):
    """Stream to dest.part, then rename. Three attempts, loud on failure."""
    if OFFLINE:
        sys.exit(f"  --offline, and {os.path.relpath(dest, ROOT)} is not cached")
    headers = {"User-Agent": UA}
    if gzip_ok:
        headers["Accept-Encoding"] = "gzip"
    last = None
    for attempt in range(1, 4):
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=120) as r:
                total = int(r.headers.get("Content-Length") or 0)
                gz = r.headers.get("Content-Encoding") == "gzip"
                tmp = dest + ".part"
                got, t0, shown = 0, time.time(), 0
                with open(tmp, "wb") as fh:
                    while True:
                        chunk = r.read(1 << 16)
                        if not chunk:
                            break
                        fh.write(chunk)
                        got += len(chunk)
                        if total > 8_000_000 and got - shown >= 8_000_000:
                            shown = got
                            print(f"        {label}: {got/1e6:5.1f} / {total/1e6:.1f} MB "
                                  f"({got/1e6/max(time.time()-t0, 1e-6):.1f} MB/s)", flush=True)
            if gz:
                import gzip
                with gzip.open(tmp, "rb") as src, open(tmp + ".u", "wb") as dst:
                    shutil.copyfileobj(src, dst)
                os.replace(tmp + ".u", tmp)
            if total and not gz and got != total:
                raise IOError(f"short read {got} of {total} bytes")
            os.replace(tmp, dest)
            return
        except Exception as exc:                                  # noqa: BLE001
            last = exc
            print(f"  warn  {label}: attempt {attempt} failed: {exc}", flush=True)
            time.sleep(3 * attempt)
    sys.exit(f"  could not download {url}: {last}")


def verify(name):
    """None if the extracted file is exactly the pinned one, else the reason."""
    path = os.path.join(OUT, name)
    if not os.path.exists(path):
        return "missing"
    got = sha256(path)
    if got != pinned[name][0]:
        return f"sha256 {got[:16]}… != pinned {pinned[name][0][:16]}…"
    return None


# -- 1. manifest -------------------------------------------------------------
need = [n for n in pinned if verify(n)]
if not os.path.exists(MANIFEST) or (need and not OFFLINE):
    download(f"{DUMPS}/manifest.json", MANIFEST, "manifest.json")
manifest = json.load(open(MANIFEST, encoding="utf-8"))
version = manifest.get("version", "?")
books = {b["name"]: b for b in manifest.get("translation_books", [])}
print(f"  ok    manifest.json · dump version {version} · "
      f"{len(books)} translation books listed")

# -- 2. the 22 files ---------------------------------------------------------
if not need:
    print(f"  ok    all {len(pinned)} pinned translations already present and verified "
          f"(cached, nothing downloaded)")
else:
    print(f"  ..    {len(need)} of {len(pinned)} translation files to fetch")
    if PER_FILE:
        for name in need:
            url = books.get(name, {}).get("url") or f"{HOST}/translation-books/{name}"
            url = url.replace("http://localhost", HOST)   # the manifest's URLs are wrong
            download(url, os.path.join(OUT, name), name, gzip_ok=True)
            time.sleep(0.5)
    else:
        zip_ok = False
        if os.path.exists(ZIP):
            try:
                with zipfile.ZipFile(ZIP) as z:
                    zip_ok = all(n in z.namelist() for n in need)
            except zipfile.BadZipFile:
                zip_ok = False
        if not zip_ok:
            size = (manifest.get("archives", {}).get("translations", {}) or {}).get("bytes")
            print(f"  ..    downloading translations-all.zip"
                  + (f" ({size/1e6:.0f} MB)" if size else ""), flush=True)
            download(f"{DUMPS}/translations-all.zip", ZIP, "translations-all.zip")
        with zipfile.ZipFile(ZIP) as z:
            for name in need:
                # ZipFile.read() checks each member's CRC-32 and raises on damage.
                data = z.read(name)
                with open(os.path.join(OUT, name), "wb") as fh:
                    fh.write(data)
            if "LICENSE.md" in z.namelist():
                with open(os.path.join(OUT, "LICENSE.md"), "wb") as fh:
                    fh.write(z.read("LICENSE.md"))
        print(f"  ok    extracted {len(need)} files from translations-all.zip "
              f"(CRC-32 checked)")

# -- 3. verify every file, twice ----------------------------------------------
bad = []
for name, (sha, lang) in sorted(pinned.items(), key=lambda kv: int(kv[0].split(".")[0])):
    path = os.path.join(OUT, name)
    size = os.path.getsize(path) if os.path.exists(path) else -1
    listed = books.get(name)
    if listed is None:
        bad.append(f"{name}: not listed in manifest {version}")
        continue
    if listed.get("bytes") != size:
        bad.append(f"{name}: {size} bytes, manifest {version} says {listed.get('bytes')}")
        continue
    why = verify(name)
    if why:
        if ACCEPT_NEW:
            print(f"  warn  {name}: {why} — accepted (MIZAN_ACCEPT_NEW_DUMP=1)")
        else:
            bad.append(f"{name}: {why}")
            # Quarantine it so nothing can index it by accident.
            os.replace(path, path + ".rejected")
        continue
    print(f"  ok    {name:11s} {lang}  {size:>10,} B  sha256 {sha[:12]}…  "
          f"{listed.get('title', '')[:40]}")
extra = sorted(f for f in os.listdir(OUT) if f.endswith(".json") and f not in pinned)
if extra:
    bad.append(f"unexpected files in data/raw/quranpedia/ would be indexed: {extra}")
if bad:
    print("\n  CHECKSUM / MANIFEST MISMATCH — refusing to build an index from these files:")
    for b in bad:
        print(f"    - {b}")
    print("\n  If Quranpedia corrected a translation, that is expected over time: re-run"
          "\n  with MIZAN_ACCEPT_NEW_DUMP=1, then re-measure (`make eval`) and update the"
          "\n  pins in scripts/setup.sh. Never publish old numbers against new text.")
    sys.exit(1)
print(f"  ok    {len(pinned)}/{len(pinned)} verified: size = manifest, SHA-256 = pinned "
      f"(pins from dump {os.environ['QP_PINNED_VERSION']}, current dump {version})")
PY

if [ "$CHANGES" = 1 ] && [ "$MIZAN_OFFLINE" = 0 ]; then
  "$PY" - <<'PY' || warn "changes endpoint not reachable — skipped (not required)"
import json, os, urllib.request
since = os.environ["QP_PINNED_VERSION"]
url = f"{os.environ['QP_HOST']}/api/v1/changes?since={since}"
req = urllib.request.Request(url, headers={"User-Agent": os.environ["MIZAN_UA"]})
with urllib.request.urlopen(req, timeout=30) as r:
    d = json.load(r)
ch = d.get("changes", {})
n = {k: (v or {}).get("count", 0) for k, v in ch.items()}
relevant = n.get("ayah_book_contents", 0) + n.get("books", 0)
msg = ", ".join(f"{k} {v}" for k, v in n.items())
if relevant:
    print(f"  warn  Quranpedia reports changes since {since}: {msg}.\n"
          f"        The pins still guarantee the measured text; refresh deliberately.")
else:
    print(f"  ok    Quranpedia changes since {since}: none affecting translations ({msg})")
PY
fi

# =============================================================================
step 3/7 "Tanzil Quran text (Arabic source, verbatim)"
# =============================================================================
"$PY" - <<'PY' || die "Tanzil text could not be fetched or verified (see above)."
import hashlib, os, sys, time, urllib.parse, urllib.request

ROOT = os.environ["MIZAN_ROOT"]
OFFLINE = os.environ["MIZAN_OFFLINE"] == "1"
CACHE = os.path.join(ROOT, "data", "raw", "tanzil")
pinned = {}
for line in os.environ["TANZIL_PINNED"].strip().splitlines():
    sha, ed = line.split()
    pinned[ed] = sha


def verse_sha(path):
    text = open(path, encoding="utf-8").read()
    lines = [ln for ln in text.splitlines() if ln.strip() and not ln.startswith("#")]
    return hashlib.sha256("\n".join(lines).encode("utf-8")).hexdigest(), len(lines)


for ed, want in pinned.items():
    path = os.path.join(CACHE, f"{ed}.txt")
    if os.path.exists(path) and verse_sha(path)[0] == want:
        print(f"  ok    {ed:13s} cached and verified")
        continue
    if OFFLINE:
        sys.exit(f"  --offline, and {ed} is missing or does not verify")
    body = urllib.parse.urlencode(
        {"quranType": ed, "outType": "txt-2", "agree": "true"}).encode()
    req = urllib.request.Request(os.environ["TANZIL_URL"], data=body,
                                 headers={"User-Agent": os.environ["MIZAN_UA"]})
    with urllib.request.urlopen(req, timeout=120) as r:
        raw = r.read().decode("utf-8")
    with open(path + ".part", "w", encoding="utf-8") as fh:
        fh.write(raw)
    got, n = verse_sha(path + ".part")
    if got != want:
        sys.exit(f"  {ed}: {n} verse lines, sha256 {got[:16]}… != pinned {want[:16]}…\n"
                 f"  Tanzil may have published a correction; refusing to continue.")
    os.replace(path + ".part", path)
    print(f"  ok    {ed:13s} downloaded · {n:,} verse lines · sha256 = pinned")
    time.sleep(1)
PY

# =============================================================================
step 4/7 "Index (data/corpus.sqlite)"
# =============================================================================
fingerprint_ok() {
  PYTHONPATH="$ROOT/src" "$PY" -m mizan.eval --check-index >/dev/null 2>&1
}
if [ "$FORCE" = 0 ] && [ -f data/corpus.sqlite ] && fingerprint_ok; then
  ok "data/corpus.sqlite already matches the reference fingerprint — not rebuilt (use --force)"
else
  rm -f data/corpus.sqlite data/corpus.sqlite-wal data/corpus.sqlite-shm
  "$PY" scripts/build_index.py  | sed 's/^/        /' || die "scripts/build_index.py failed"
  "$PY" scripts/fetch_arabic.py | sed 's/^/        /' || die "scripts/fetch_arabic.py failed"
  ok "index built"
fi

# =============================================================================
step 5/7 "Verify the index against the reference"
# =============================================================================
if OUT=$(PYTHONPATH="$ROOT/src" "$PY" -m mizan.eval --check-index 2>&1); then
  MIZAN_CHECK="$OUT" "$PY" - <<'PY'
import json, os
d = json.loads(os.environ["MIZAN_CHECK"].splitlines()[0])
langs = " ".join(f"{k}:{v}" for k, v in d["languages"].items())
print(f"  ok    {d['translations']} translations ({langs}) · {d['renderings']:,} renderings"
      f" · {d['arabic_verses']:,} Arabic verses · dump {d['version']}")
print(f"  ok    fingerprint {d['fingerprint'][:24]}… = reference index")
PY
else
  echo "$OUT" | sed 's/^/        /'
  if [ "${MIZAN_ALLOW_INDEX_DRIFT:-0}" = 1 ]; then
    warn "index differs from the reference (MIZAN_ALLOW_INDEX_DRIFT=1) — published numbers will not reproduce"
  else
    die "the built index differs from the reference index the published numbers were measured on.
       Did scripts/build_index.py, engine.normalize or a source file change?
       (MIZAN_ALLOW_INDEX_DRIFT=1 downgrades this to a warning.)"
  fi
fi

# =============================================================================
step 6/7 "Terminology glossary (الجمهرة — redistributable form)"
# =============================================================================
# The repository carries data/glossary/jamhara.public.jsonl: term <-> approved
# English + source URL, without the dictionary's prose definitions (its terms
# grant personal, non-commercial use only). A maintainer who has re-collected
# the dictionary (scripts/fetch_jamhara.py -> jamhara.jsonl, kept local)
# regenerates the public file here.
if [ -f data/glossary/jamhara.jsonl ] && [ -f scripts/export_public_glossary.py ]; then
  "$PY" scripts/export_public_glossary.py | sed 's/^/        /' \
    || die "scripts/export_public_glossary.py failed"
  ok "data/glossary/jamhara.public.jsonl regenerated from the local jamhara.jsonl"
elif [ -f data/glossary/jamhara.public.jsonl ]; then
  ok "data/glossary/jamhara.public.jsonl present ($(wc -l < data/glossary/jamhara.public.jsonl | tr -d ' ') records)"
else
  warn "no glossary in data/glossary/ — the terminology panel will use its small built-in list"
fi

# =============================================================================
step 7/7 "Real-world test corpus (data/real/ — third-party text, not committed)"
# =============================================================================
if [ "$REAL" = 1 ]; then
  ARGS=""; [ "$MIZAN_OFFLINE" = 1 ] && ARGS="--offline"
  "$PY" scripts/rebuild_real_corpus.py $ARGS || die "real-corpus rebuild failed"
elif [ -f data/real/corpus.jsonl ]; then
  ok "data/real/corpus.jsonl present"
else
  warn "data/real/corpus.jsonl not built — the real/fp/clarity eval suites will be skipped."
  printf '        Rebuild it from the publishers'"'"' pages: %smake real-corpus%s (~10 min, polite crawl)\n' "$B" "$N"
fi

printf '\n%sMIZAN is ready%s in %ss.\n' "$G" "$N" "$(( $(date +%s) - START ))"
printf '  run the app      make run            (http://127.0.0.1:%s)\n' "${MIZAN_PORT:-8000}"
printf '  run the tests    make test\n'
printf '  re-derive        make eval           (python3 -m mizan.eval --suite all --runs 3)\n'
